---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __APPNAME__-dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
      - name: __APP_NAME__-ctr
        image: __IMAGE__:__VERSION__
        imagePullPolicy: Always